// modules/video.js
export const MUTATION_SET_VIDEOS = "MUTATION_SET_VIDEOS";
export const MUTATION_SET_FILTEREDVIDEOS = "MUTATION_SET_FILTEREDVIDEOS";
export const MUTATION_APPLY_FILTER = "MUTATION_APPLYFILTER";
